### ISSUE TITLE
Configuration setting not preserved

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/config-ini#7]
I don't understand why this is happening, but in this case I expect `database` to be assigned the value `foo` in the updated version, rather than `janadb`:
```
*Data.Ini.Config.Bidir Data.Text> updateIniFile defaultConfig parseConfig (pack "[misc]\ndatabase = foo\n") defaultUpdatePolicy
Right "[misc]\ndatabase = janadb\n"
```

**Comment by aisamanra** [comment]
We've talked about this out-of-band; I believe this issue should be resolved with an API change that allows you to be more granular about what is considered a "default" value versus an "updated" value.
