### ISSUE TITLE
Optional settings only reinstated in explicit sections

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/config-ini#8]
Observed behavior: enabling default settings to be emitted only does so for sections that are already present in the input.

Expected/assumed behavior: that doing this without explicitly mentioning all sections would result in the emission of all other sections along with their defaults to form a fully-populated configuration.

(There are two sections in the specification that are not present in the output below.)

```
*Data.Ini.Config.Bidir Data.Text> updateIniFile defaultConfig parseConfig (pack "[misc]\ndatabase = foo\n") (UpdatePolicy True False CommentPolicyNone)
Right "[misc]\ndatabase = janadb\nbackend = any\ntmux-session-name = jana\nescrow-path = spdz-keys\nproject-root = .\nlog-directory = logs\n"
```

**Comment by aisamanra** [comment]
This has been addressed with the new API on the bidir branch, and works in my tests now.
